-- CreateEnum
CREATE TYPE "Category" AS ENUM ('ENVIRONMENTAL_ISSUES', 'PUBLIC_SAFETY', 'PUBLIC_HEALTH', 'TRANSPORTATION', 'HOUSING', 'EDUCATION', 'ECONOMY', 'SOCIAL_WELFARE');

-- AlterTable
ALTER TABLE "Issue" ADD COLUMN     "category" "Category";
